name: Build IceCat
on: push
jobs:
 build:
  runs-on: macos-latest
  steps:
    - name: Disable spotlight
      run: |
        sudo mdutil -a -i off
    - name: SDK
      run: |
        wget https://github.com/phracker/MacOSX-SDKs/releases/download/11.0-11.1/MacOSX10.11.sdk.tar.xz
        tar xf MacOSX10.11.sdk.tar.xz
        mv MacOSX10.11.sdk/ /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/
    - name: Installation depends
      run: |
        brew install yasm mercurial gawk ccache python autoconf@2.13 rust nasm node
        cargo install cbindgen
    - name: Download source code
      run: |
        wget https://github.com/xyxloop/icecat/releases/download/v78.9/icecat-78.9.0-rh1.tar.bz2
        tar xjf icecat-78.9.0-rh1.tar.bz2
    - name: Build
      run: |
        cd icecat-78.9.0
        mkdir -vp objdir
        cd objdir
        ../configure --with-l10n-base=../l10n --enable-official-branding --with-macos-sdk=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk
        make -j3
    - name: Build package
      run: |
        cd icecat-78.9.0/objdir
        make package
    - name : Upload artifact
      uses: actions/upload-artifact@master
      with:
        name: IceCat
        path: icecat-78.9.0/objdir/dist
      
