name: Build IceCat
on: push
jobs:
 build:
  runs-on: macos-latest
  steps:
    - name: SDK
      run: |
        wget https://github.com/phracker/MacOSX-SDKs/releases/download/11.0-11.1/MacOSX10.11.sdk.tar.xz
        tar xf MacOSX10.11.sdk.tar.xz
        mv MacOSX10.11.sdk/ /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/
    - name: Installation depends
      run: |
        brew install yasm mercurial gawk ccache python autoconf@2.13 rust nasm node
        cargo install cbindgen
    - name: Download source code and build
      run: |
        git clone https://github.com/xyxloop/Icecat-mac
        cd Icecat-mac/building
        ./icebuild.sh
    - name : Upload artifact
      uses: actions/upload-artifact@master
      with:
        name: IceCat
        path: Icecat-mac/icecat-78.9.0/objdir/dist
      
