name: Build IceCat
on: 
 release:
    types: [published]
jobs:
 build:
  runs-on: macos-latest
  steps:
    - name: SDK
      run: |
        wget https://github.com/phracker/MacOSX-SDKs/releases/download/11.0-11.1/MacOSX10.11.sdk.tar.xz
        tar xf MacOSX10.11.sdk.tar.xz
        mv MacOSX10.11.sdk/ /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/
    - name: Installation depends
      run: |
        brew install yasm autoconf@2.13
    - name: Download source code and build
      run: |
        wget https://raw.githubusercontent.com/xyxloop/icecat/main/icebuild
        chmod +x ./icebuild
        ./icebuild
    - name : Upload artifact
      uses: actions/upload-artifact@master
      with:
        name: IceCat
        path: icecat-60.7.0//objdir/dist
      
