name: Build IceCat
on: workflow_dispatch
jobs:
 build:
  runs-on: macos-11
  name: Build IceCat for macOS arm64
  steps:
    - name: Disable spotlight
      run: |
        sudo mdutil -a -i off
    - name: SDK
      run: |
        wget -q https://github.com/phracker/MacOSX-SDKs/releases/download/11.3/MacOSX11.0.sdk.tar.xz
        tar xf MacOSX11.0.sdk.tar.xz 
        mv MacOSX11.0.sdk/ /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/
    - name: Installation depends
      run: |
        brew install yasm mercurial gawk ccache autoconf@2.13 rust nasm node
    - name: Download source code
      run: |
        wget -q https://github.com/xyxloop/icecattarball/releases/download/91.5.1-gnu1/icecat-91.5.1-gnu1.tar.bz2
        tar xjf icecat-91.5.1-gnu1.tar.bz2
        wget -q https://raw.githubusercontent.com/elsorino/Icecat-mac/master/building/icecat.icns
        cp ./icecat.icns icecat-91.5.1/browser/branding/official/icecat.icns
    - name: Configure
      run: |
        cd icecat-91.5.1
        mkdir -vp objdir
        cd objdir
        rustup target add aarch64-apple-darwin
        python3 ../configure.py --target=aarch64-apple-darwin --with-l10n-base=../l10n --enable-official-branding --with-macos-sdk=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.0.sdk --disable-update-agent --disable-updater
    - name: Build
      run: |
        cd icecat-91.5.1/objdir
        make -j3
    - name: Build package
      run: |
        cd icecat-91.5.1/objdir
        make package
    - name : Upload artifact
      uses: actions/upload-artifact@master
      with:
        name: icecat-91.5.1.en-US.mac.dmg
        path: icecat-91.5.1/objdir/dist/icecat-91.5.1.en-US.mac.dmg
