name: Build IceCat
on: push
jobs:
 build:
  runs-on: macos-latest
  steps:
    - name: Installation depends
      run: |
        brew install yasm autoconf@2.13
    - name: Download source code
      run: |
        wget https://ftp.gnu.org/gnu/gnuzilla/60.7.0/icecat-60.7.0-gnu1.tar.bz2
        tar xfj icecat-60.7.0-gnu1.tar.bz2
    - name: Prepare environment
      run: |
        cd icecat-60.7.0
        mkdir objdir
        mkdir -p ./browser/branding/unofficial/moz.build
        cd objdir
        ../configure CC=/usr/local/bin/gcc CXX=/usr/local/bin/g++ --with-l10n-base=../l10n --enable-official-branding
    - name: Build
      run: |
        cd icecat-60.7.0
        make -j$(nproc)
    - name : Upload artifact
      uses: actions/upload-artifact@master
      with:
        name: IceCat
        path: icecat-60.7.0/dist
      
